global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#rootbe'
