version: '3.3'
services:
  post_db:
    image: mongo:3.2
    container_name: mongo_db
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    image: ${USER_NAME}/ui:${UI_VER}
    container_name: ui
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - front_net

  post:
    image: ${USER_NAME}/post:${POST_VER}
    container_name: post
    networks:
      - back_net
      - front_net

  comment:
    image: ${USER_NAME}/comment:${COMMENT_VER}
    container_name: comment
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  front_net:
  back_net:
